# Generated by Django 3.0.4 on 2020-03-20 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='words',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=100)),
                ('word', models.CharField(max_length=50)),
                ('count', models.IntegerField()),
            ],
        ),
    ]
